import Foundation

// Native interface translations shared with the approved design.
enum InterfaceText {
    static let translations: [String: [String: String]] = [
"en": [
"全部": "All",
"最近使用": "Recent",
"标签": "Tags",
"用逗号分隔标签": "Separate tags with commas",

"磨砂玻璃": "Frosted glass",
"液态玻璃": "Liquid Glass",
"玻璃样式": "Glass style",
"Vim 编辑模式": "Vim editing",
"普通模式": "Normal",
"插入模式": "Insert",
"保存未完成的修改？": "Save your changes?",
"快捷键方案": "Key bindings",
"返回": "Back",
"展开": "Expand",
"搜索短语": "Search phrases",
"新建短语": "New phrase",
"新建短语（⌘N）": "New phrase (⌘N)",
"编辑短语": "Edit phrase",
"编辑短语（⌘E）": "Edit phrase (⌘E)",
"设置": "Settings",
"设置（⌘,）": "Settings (⌘,)",
"返回短语": "Back to phrases",
"短语正文": "Phrase text",
"输入短语正文…": "Enter phrase text…",
"置顶": "Pin",
"删除短语": "Delete phrase",
"取消": "Cancel",
"保存": "Save",
"⌘S 保存": "⌘S Save",
"完成": "Done",
"更改后自动保存": "Changes save automatically",
"呼出快捷键": "Shortcut",
"浮窗大小": "Window size",
"小": "S",
"中": "M",
"大": "L",
"外观": "Appearance",
"语言": "Language",
"跟随系统": "System",
"浅色": "Light",
"深色": "Dark",
"登录时启动": "Launch at login",
"辅助功能权限": "Accessibility",
"配置文件": "Configuration",
"打开": "Open",
"已授权 ›": "Allowed ›",
"去授权 ›": "Allow access ›",
"请在系统设置中批准登录项": "Approve the login item in System Settings",
"⌘N 新建  ·  ⌘E 编辑  ·  ↵ 插入": "⌘N New  ·  ⌘E Edit  ·  ↵ Insert",
"没有匹配的短语": "No matching phrases",
"还没有短语": "No phrases yet",
" 条": " items",
" 字符": " characters",
"已保存": "Saved",
"未保存": "Unsaved",
"已删除": "Deleted",
"请输入短语正文": "Enter phrase text first",
"放弃未保存的修改？": "Discard unsaved changes?",
"当前修改尚未保存。": "Your changes have not been saved.",
"放弃修改": "Discard",
"继续编辑": "Keep editing",
"删除这条短语？": "Delete this phrase?",
"删除后无法恢复。": "This cannot be undone.",
"删除": "Delete",
"按下组合键…": "Press shortcut…",
"请包含 ⌘ / ⌃ / ⌥": "Include ⌘ / ⌃ / ⌥",
"短语": "Phrase",
"⌃B 返回": "⌃B Back",
"纯文本": "Plain text",
"编辑": "Edit",
"插入": "Insert"
],
"zh-Hant": [
"全部": "全部",
"最近使用": "最近使用",
"标签": "標籤",
"用逗号分隔标签": "以逗號分隔標籤",

"磨砂玻璃": "磨砂玻璃",
"液态玻璃": "液態玻璃",
"玻璃样式": "玻璃樣式",
"Vim 编辑模式": "Vim 編輯模式",
"普通模式": "普通模式",
"插入模式": "插入模式",
"保存未完成的修改？": "儲存尚未完成的變更？",
"快捷键方案": "快捷鍵方案",
"展开": "展開",
"搜索短语": "搜尋短語",
"新建短语": "新增短語",
"编辑短语": "編輯短語",
"设置": "設定",
"返回短语": "返回短語",
"短语正文": "短語內容",
"输入短语正文…": "輸入短語內容…",
"置顶": "置頂",
"删除短语": "刪除短語",
"取消": "取消",
"保存": "儲存",
"完成": "完成",
"更改后自动保存": "變更後自動儲存",
"呼出快捷键": "叫出快捷鍵",
"浮窗大小": "浮窗大小",
"小": "小",
"中": "中",
"大": "大",
"外观": "外觀",
"语言": "語言",
"跟随系统": "跟隨系統",
"浅色": "淺色",
"深色": "深色",
"登录时启动": "登入時啟動",
"辅助功能权限": "輔助使用權限",
"配置文件": "設定檔",
"打开": "開啟",
"已授权 ›": "已授權 ›",
"去授权 ›": "前往授權 ›",
"请在系统设置中批准登录项": "請在系統設定中核准登入項目",
"没有匹配的短语": "沒有符合的短語",
"还没有短语": "尚無短語",
" 条": " 條",
" 字符": " 字元",
"已保存": "已儲存",
"未保存": "未儲存",
"已删除": "已刪除",
"请输入短语正文": "請先輸入短語內容",
"放弃未保存的修改？": "捨棄未儲存的變更？",
"当前修改尚未保存。": "目前變更尚未儲存。",
"放弃修改": "捨棄變更",
"继续编辑": "繼續編輯",
"删除这条短语？": "刪除此短語？",
"删除后无法恢复。": "刪除後無法復原。",
"删除": "刪除",
"按下组合键…": "按下組合鍵…",
"请包含 ⌘ / ⌃ / ⌥": "請包含 ⌘ / ⌃ / ⌥",
"短语": "短語",
"纯文本": "純文字",
"编辑": "編輯",
"插入": "插入",
"返回": "返回",
"新建": "新增",
"新建短语（⌘N）": "新增短語 (⌘N)",
"编辑短语（⌘E）": "編輯短語 (⌘E)",
"设置（⌘,）": "設定 (⌘,)",
"⌘S 保存": "⌘S 儲存",
"⌃B 返回": "⌃B 返回",
"⌘N 新建  ·  ⌘E 编辑  ·  ↵ 插入": "⌘N 新增  ·  ⌘E 編輯  ·  ↵ 插入"
],
"ja": [
"全部": "すべて",
"最近使用": "最近使用",
"标签": "タグ",
"用逗号分隔标签": "タグをカンマで区切る",

"磨砂玻璃": "すりガラス",
"液态玻璃": "Liquid Glass",
"玻璃样式": "ガラスのスタイル",
"Vim 编辑模式": "Vim 編集モード",
"普通模式": "ノーマル",
"插入模式": "挿入",
"保存未完成的修改？": "変更を保存しますか？",
"快捷键方案": "キー設定",
"展开": "展開",
"搜索短语": "フレーズを検索",
"新建短语": "新規フレーズ",
"编辑短语": "フレーズを編集",
"设置": "設定",
"返回短语": "一覧に戻る",
"短语正文": "フレーズ本文",
"输入短语正文…": "本文を入力…",
"置顶": "固定",
"删除短语": "フレーズを削除",
"取消": "キャンセル",
"保存": "保存",
"完成": "完了",
"更改后自动保存": "変更は自動保存されます",
"呼出快捷键": "ショートカット",
"浮窗大小": "ウィンドウサイズ",
"小": "小",
"中": "中",
"大": "大",
"外观": "外観",
"语言": "言語",
"跟随系统": "システムに従う",
"浅色": "ライト",
"深色": "ダーク",
"登录时启动": "ログイン時に起動",
"辅助功能权限": "アクセシビリティ",
"配置文件": "設定ファイル",
"打开": "開く",
"已授权 ›": "許可済み ›",
"去授权 ›": "許可する ›",
"请在系统设置中批准登录项": "システム設定でログイン項目を許可してください",
"没有匹配的短语": "一致するフレーズがありません",
"还没有短语": "フレーズはまだありません",
" 条": " 件",
" 字符": " 文字",
"已保存": "保存済み",
"未保存": "未保存",
"已删除": "削除済み",
"请输入短语正文": "本文を入力してください",
"放弃未保存的修改？": "未保存の変更を破棄しますか？",
"当前修改尚未保存。": "変更は保存されていません。",
"放弃修改": "破棄",
"继续编辑": "編集を続ける",
"删除这条短语？": "このフレーズを削除しますか？",
"删除后无法恢复。": "この操作は取り消せません。",
"删除": "削除",
"按下组合键…": "キーを押してください…",
"请包含 ⌘ / ⌃ / ⌥": "⌘ / ⌃ / ⌥ を含めてください",
"短语": "フレーズ",
"纯文本": "プレーンテキスト",
"编辑": "編集",
"插入": "挿入",
"返回": "戻る",
"新建": "新規",
"新建短语（⌘N）": "新規フレーズ (⌘N)",
"编辑短语（⌘E）": "フレーズを編集 (⌘E)",
"设置（⌘,）": "設定 (⌘,)",
"⌘S 保存": "⌘S 保存",
"⌃B 返回": "⌃B 戻る",
"⌘N 新建  ·  ⌘E 编辑  ·  ↵ 插入": "⌘N 新規  ·  ⌘E 編集  ·  ↵ 挿入"
],
"ko": [
"全部": "전체",
"最近使用": "최근 사용",
"标签": "태그",
"用逗号分隔标签": "쉼표로 태그 구분",

"磨砂玻璃": "반투명 유리",
"液态玻璃": "Liquid Glass",
"玻璃样式": "글래스 스타일",
"Vim 编辑模式": "Vim 편집 모드",
"普通模式": "일반 모드",
"插入模式": "입력 모드",
"保存未完成的修改？": "변경 사항을 저장할까요?",
"快捷键方案": "키 설정",
"展开": "펼치기",
"搜索短语": "문구 검색",
"新建短语": "새 문구",
"编辑短语": "문구 편집",
"设置": "설정",
"返回短语": "목록으로 돌아가기",
"短语正文": "문구 내용",
"输入短语正文…": "내용 입력…",
"置顶": "고정",
"删除短语": "문구 삭제",
"取消": "취소",
"保存": "저장",
"完成": "완료",
"更改后自动保存": "변경 사항이 자동 저장됩니다",
"呼出快捷键": "단축키",
"浮窗大小": "창 크기",
"小": "작게",
"中": "보통",
"大": "크게",
"外观": "화면 모드",
"语言": "언어",
"跟随系统": "시스템 설정",
"浅色": "라이트",
"深色": "다크",
"登录时启动": "로그인 시 실행",
"辅助功能权限": "손쉬운 사용 권한",
"配置文件": "설정 파일",
"打开": "열기",
"已授权 ›": "허용됨 ›",
"去授权 ›": "권한 허용 ›",
"请在系统设置中批准登录项": "시스템 설정에서 로그인 항목을 허용하세요",
"没有匹配的短语": "일치하는 문구가 없습니다",
"还没有短语": "아직 문구가 없습니다",
" 条": "개",
" 字符": "자",
"已保存": "저장됨",
"未保存": "저장 안 됨",
"已删除": "삭제됨",
"请输入短语正文": "내용을 입력하세요",
"放弃未保存的修改？": "저장하지 않은 변경 사항을 버릴까요?",
"当前修改尚未保存。": "변경 사항이 저장되지 않았습니다.",
"放弃修改": "버리기",
"继续编辑": "계속 편집",
"删除这条短语？": "이 문구를 삭제할까요?",
"删除后无法恢复。": "이 작업은 되돌릴 수 없습니다.",
"删除": "삭제",
"按下组合键…": "단축키를 누르세요…",
"请包含 ⌘ / ⌃ / ⌥": "⌘ / ⌃ / ⌥를 포함하세요",
"短语": "문구",
"纯文本": "일반 텍스트",
"编辑": "편집",
"插入": "삽입",
"返回": "뒤로",
"新建": "새로 만들기",
"新建短语（⌘N）": "새 문구 (⌘N)",
"编辑短语（⌘E）": "문구 편집 (⌘E)",
"设置（⌘,）": "설정 (⌘,)",
"⌘S 保存": "⌘S 저장",
"⌃B 返回": "⌃B 뒤로",
"⌘N 新建  ·  ⌘E 编辑  ·  ↵ 插入": "⌘N 새로 만들기  ·  ⌘E 편집  ·  ↵ 삽입"
],
"fr": [
"全部": "Tous",
"最近使用": "Récents",
"标签": "Tags",
"用逗号分隔标签": "Séparer les tags par des virgules",

"磨砂玻璃": "Verre dépoli",
"液态玻璃": "Verre liquide",
"玻璃样式": "Style de verre",
"Vim 编辑模式": "Édition Vim",
"普通模式": "Normal",
"插入模式": "Insertion",
"保存未完成的修改？": "Enregistrer les modifications ?",
"快捷键方案": "Raccourcis",
"展开": "Développer",
"搜索短语": "Rechercher des expressions",
"新建短语": "Nouveau texte",
"编辑短语": "Modifier le texte",
"设置": "Réglages",
"返回短语": "Retour aux textes",
"短语正文": "Contenu du texte",
"输入短语正文…": "Saisir le texte…",
"置顶": "Épingler",
"删除短语": "Supprimer le texte",
"取消": "Annuler",
"保存": "Enregistrer",
"完成": "Terminé",
"更改后自动保存": "Enregistrement automatique",
"呼出快捷键": "Raccourci",
"浮窗大小": "Taille de fenêtre",
"小": "P",
"中": "M",
"大": "G",
"外观": "Apparence",
"语言": "Langue",
"跟随系统": "Système",
"浅色": "Clair",
"深色": "Sombre",
"登录时启动": "Ouvrir à la connexion",
"辅助功能权限": "Accessibilité",
"配置文件": "Configuration",
"打开": "Ouvrir",
"已授权 ›": "Autorisé ›",
"去授权 ›": "Autoriser ›",
"请在系统设置中批准登录项": "Autorisez l’ouverture à la connexion dans les Réglages Système",
"没有匹配的短语": "Aucun résultat",
"还没有短语": "Aucun texte",
" 条": " textes",
" 字符": " caractères",
"已保存": "Enregistré",
"未保存": "Non enregistré",
"已删除": "Supprimé",
"请输入短语正文": "Saisissez le contenu du texte",
"放弃未保存的修改？": "Abandonner les modifications ?",
"当前修改尚未保存。": "Les modifications ne sont pas enregistrées.",
"放弃修改": "Abandonner",
"继续编辑": "Continuer à modifier",
"删除这条短语？": "Supprimer ce texte ?",
"删除后无法恢复。": "Cette action est irréversible.",
"删除": "Supprimer",
"按下组合键…": "Appuyez sur les touches…",
"请包含 ⌘ / ⌃ / ⌥": "Inclure ⌘ / ⌃ / ⌥",
"短语": "Texte",
"纯文本": "Texte brut",
"编辑": "Modifier",
"插入": "Insérer",
"返回": "Retour",
"新建": "Nouveau",
"新建短语（⌘N）": "Nouveau texte (⌘N)",
"编辑短语（⌘E）": "Modifier le texte (⌘E)",
"设置（⌘,）": "Réglages (⌘,)",
"⌘S 保存": "⌘S Enregistrer",
"⌃B 返回": "⌃B Retour",
"⌘N 新建  ·  ⌘E 编辑  ·  ↵ 插入": "⌘N Nouveau  ·  ⌘E Modifier  ·  ↵ Insérer"
],
"de": [
"全部": "Alle",
"最近使用": "Zuletzt benutzt",
"标签": "Tags",
"用逗号分隔标签": "Tags mit Kommas trennen",

"磨砂玻璃": "Milchglas",
"液态玻璃": "Flüssigglas",
"玻璃样式": "Glasstil",
"Vim 编辑模式": "Vim-Bearbeitung",
"普通模式": "Normal",
"插入模式": "Einfügen",
"保存未完成的修改？": "Änderungen speichern?",
"快捷键方案": "Tastenbelegung",
"展开": "Ausklappen",
"搜索短语": "Textn suchen",
"新建短语": "Neuer Text",
"编辑短语": "Text bearbeiten",
"设置": "Einstellungen",
"返回短语": "Zurück zur Liste",
"短语正文": "Text-Text",
"输入短语正文…": "Text eingeben…",
"置顶": "Anheften",
"删除短语": "Text löschen",
"取消": "Abbrechen",
"保存": "Speichern",
"完成": "Fertig",
"更改后自动保存": "Änderungen automatisch gespeichert",
"呼出快捷键": "Kurzbefehl",
"浮窗大小": "Fenstergröße",
"小": "K",
"中": "M",
"大": "G",
"外观": "Darstellung",
"语言": "Sprache",
"跟随系统": "System",
"浅色": "Hell",
"深色": "Dunkel",
"登录时启动": "Beim Anmelden starten",
"辅助功能权限": "Bedienungshilfen",
"配置文件": "Konfiguration",
"打开": "Öffnen",
"已授权 ›": "Erlaubt ›",
"去授权 ›": "Erlauben ›",
"请在系统设置中批准登录项": "Anmeldeobjekt in den Systemeinstellungen erlauben",
"没有匹配的短语": "Keine passenden Texte",
"还没有短语": "Noch keine Texte",
" 条": " Texte",
" 字符": " Zeichen",
"已保存": "Gespeichert",
"未保存": "Nicht gespeichert",
"已删除": "Gelöscht",
"请输入短语正文": "Bitte Text-Text eingeben",
"放弃未保存的修改？": "Änderungen verwerfen?",
"当前修改尚未保存。": "Änderungen wurden nicht gespeichert.",
"放弃修改": "Verwerfen",
"继续编辑": "Weiter bearbeiten",
"删除这条短语？": "Diesen Text löschen?",
"删除后无法恢复。": "Dies kann nicht rückgängig gemacht werden.",
"删除": "Löschen",
"按下组合键…": "Tastenkombination drücken…",
"请包含 ⌘ / ⌃ / ⌥": "⌘ / ⌃ / ⌥ verwenden",
"短语": "Text",
"纯文本": "Nur Text",
"编辑": "Bearbeiten",
"插入": "Einfügen",
"返回": "Zurück",
"新建": "Neu",
"新建短语（⌘N）": "Neuer Text (⌘N)",
"编辑短语（⌘E）": "Text bearbeiten (⌘E)",
"设置（⌘,）": "Einstellungen (⌘,)",
"⌘S 保存": "⌘S Speichern",
"⌃B 返回": "⌃B Zurück",
"⌘N 新建  ·  ⌘E 编辑  ·  ↵ 插入": "⌘N Neu  ·  ⌘E Bearbeiten  ·  ↵ Einfügen"
],
"es": [
"全部": "Todo",
"最近使用": "Recientes",
"标签": "Etiquetas",
"用逗号分隔标签": "Separar etiquetas con comas",

"磨砂玻璃": "Vidrio esmerilado",
"液态玻璃": "Vidrio líquido",
"玻璃样式": "Estilo de cristal",
"Vim 编辑模式": "Edición Vim",
"普通模式": "Normal",
"插入模式": "Inserción",
"保存未完成的修改？": "¿Guardar los cambios?",
"快捷键方案": "Atajos de teclado",
"展开": "Expandir",
"搜索短语": "Buscar frases",
"新建短语": "Nuevo texto",
"编辑短语": "Editar texto",
"设置": "Ajustes",
"返回短语": "Volver a los textos",
"短语正文": "Texto del texto",
"输入短语正文…": "Escribe el texto…",
"置顶": "Fijar",
"删除短语": "Eliminar texto",
"取消": "Cancelar",
"保存": "Guardar",
"完成": "Listo",
"更改后自动保存": "Los cambios se guardan automáticamente",
"呼出快捷键": "Atajo",
"浮窗大小": "Tamaño de ventana",
"小": "P",
"中": "M",
"大": "G",
"外观": "Apariencia",
"语言": "Idioma",
"跟随系统": "Sistema",
"浅色": "Claro",
"深色": "Oscuro",
"登录时启动": "Abrir al iniciar sesión",
"辅助功能权限": "Accesibilidad",
"配置文件": "Configuración",
"打开": "Abrir",
"已授权 ›": "Permitido ›",
"去授权 ›": "Permitir ›",
"请在系统设置中批准登录项": "Autoriza el inicio de sesión en Ajustes del Sistema",
"没有匹配的短语": "No hay coincidencias",
"还没有短语": "Aún no hay textos",
" 条": " textos",
" 字符": " caracteres",
"已保存": "Guardado",
"未保存": "Sin guardar",
"已删除": "Eliminado",
"请输入短语正文": "Escribe el texto del texto",
"放弃未保存的修改？": "¿Descartar los cambios?",
"当前修改尚未保存。": "Los cambios no se han guardado.",
"放弃修改": "Descartar",
"继续编辑": "Seguir editando",
"删除这条短语？": "¿Eliminar este texto?",
"删除后无法恢复。": "Esta acción no se puede deshacer.",
"删除": "Eliminar",
"按下组合键…": "Pulsa las teclas…",
"请包含 ⌘ / ⌃ / ⌥": "Incluye ⌘ / ⌃ / ⌥",
"短语": "Texto",
"纯文本": "Texto sin formato",
"编辑": "Editar",
"插入": "Insertar",
"返回": "Volver",
"新建": "Nuevo",
"新建短语（⌘N）": "Nuevo texto (⌘N)",
"编辑短语（⌘E）": "Editar texto (⌘E)",
"设置（⌘,）": "Ajustes (⌘,)",
"⌘S 保存": "⌘S Guardar",
"⌃B 返回": "⌃B Volver",
"⌘N 新建  ·  ⌘E 编辑  ·  ↵ 插入": "⌘N Nuevo  ·  ⌘E Editar  ·  ↵ Insertar"
],
]
}
