let interfaceLanguage = 'zh-Hans';
const englishText = {
 '搜索短语':'Search phrases','搜索提示词':'Search prompts','新建提示词':'New prompt','新建提示词（⌘N）':'New prompt (⌘N)',
 '编辑提示词':'Edit prompt','编辑提示词（⌘E）':'Edit prompt (⌘E)','设置':'Settings','设置（⌘,）':'Settings (⌘,)',
 '返回提示词':'Back to prompts','提示词正文':'Prompt text','输入提示词正文…':'Enter prompt text…','置顶':'Pin',
 '删除提示词':'Delete prompt','取消':'Cancel','保存':'Save','⌘S 保存':'⌘S Save','完成':'Done','更改后自动保存':'Changes save automatically',
 '呼出快捷键':'Shortcut','浮窗大小':'Window size','小':'S','中':'M','大':'L','外观':'Appearance','语言':'Language',
 '跟随系统':'System','浅色':'Light','深色':'Dark','登录时启动':'Launch at login','辅助功能权限':'Accessibility',
 '配置文件':'Configuration','打开':'Open','已授权 ›':'Allowed ›','去授权 ›':'Allow access ›','请在系统设置中批准登录项':'Approve the login item in System Settings',
 '⌘N 新建 · ⌘E 编辑 · ↵ 插入':'⌘N New · ⌘E Edit · ↵ Insert',
 '没有匹配的提示词':'No matching prompts','还没有提示词':'No prompts yet',' 条':' prompts',' 字符':' characters',
 '已保存':'Saved','未保存':'Unsaved','已删除':'Deleted','请输入提示词正文':'Enter prompt text first',
 '放弃未保存的修改？':'Discard unsaved changes?','当前修改尚未保存。':'Your changes have not been saved.',
 '放弃修改':'Discard','继续编辑':'Keep editing','删除这条提示词？':'Delete this prompt?','删除后无法恢复。':'This cannot be undone.','删除':'Delete',
 '按下组合键…':'Press shortcut…','请包含 ⌘ / ⌃ / ⌥':'Include ⌘ / ⌃ / ⌥','提示词':'Prompt','⌃B 返回':'⌃B Back','纯文本':'Plain text','编辑':'Edit','插入':'Insert'
};
const translatedText = {
 "zh-Hant": {
  "搜索短语": "搜尋短語",
  "搜索提示词": "搜尋提示詞",
  "新建提示词": "新增提示詞",
  "编辑提示词": "編輯提示詞",
  "设置": "設定",
  "返回提示词": "返回提示詞",
  "提示词正文": "提示詞內容",
  "输入提示词正文…": "輸入提示詞內容…",
  "置顶": "置頂",
  "删除提示词": "刪除提示詞",
  "取消": "取消",
  "保存": "儲存",
  "完成": "完成",
  "更改后自动保存": "變更後自動儲存",
  "呼出快捷键": "叫出快捷鍵",
  "浮窗大小": "浮窗大小",
  "小": "小",
  "中": "中",
  "大": "大",
  "外观": "外觀",
  "语言": "語言",
  "跟随系统": "跟隨系統",
  "浅色": "淺色",
  "深色": "深色",
  "登录时启动": "登入時啟動",
  "辅助功能权限": "輔助使用權限",
  "配置文件": "設定檔",
  "打开": "開啟",
  "已授权 ›": "已授權 ›",
  "去授权 ›": "前往授權 ›",
  "请在系统设置中批准登录项": "請在系統設定中核准登入項目",
  "没有匹配的提示词": "沒有符合的提示詞",
  "还没有提示词": "尚無提示詞",
  " 条": " 條",
  " 字符": " 字元",
  "已保存": "已儲存",
  "未保存": "未儲存",
  "已删除": "已刪除",
  "请输入提示词正文": "請先輸入提示詞內容",
  "放弃未保存的修改？": "捨棄未儲存的變更？",
  "当前修改尚未保存。": "目前變更尚未儲存。",
  "放弃修改": "捨棄變更",
  "继续编辑": "繼續編輯",
  "删除这条提示词？": "刪除此提示詞？",
  "删除后无法恢复。": "刪除後無法復原。",
  "删除": "刪除",
  "按下组合键…": "按下組合鍵…",
  "请包含 ⌘ / ⌃ / ⌥": "請包含 ⌘ / ⌃ / ⌥",
  "提示词": "提示詞",
  "纯文本": "純文字",
  "编辑": "編輯",
  "插入": "插入",
  "返回": "返回",
  "新建": "新增",
  "新建提示词（⌘N）": "新增提示詞 (⌘N)",
  "编辑提示词（⌘E）": "編輯提示詞 (⌘E)",
  "设置（⌘,）": "設定 (⌘,)",
  "⌘S 保存": "⌘S 儲存",
  "⌃B 返回": "⌃B 返回",
  "⌘N 新建 · ⌘E 编辑 · ↵ 插入": "⌘N 新增 · ⌘E 編輯 · ↵ 插入"
 },
 "ja": {
  "搜索短语": "フレーズを検索",
  "搜索提示词": "プロンプトを検索",
  "新建提示词": "新規プロンプト",
  "编辑提示词": "プロンプトを編集",
  "设置": "設定",
  "返回提示词": "一覧に戻る",
  "提示词正文": "プロンプト本文",
  "输入提示词正文…": "本文を入力…",
  "置顶": "固定",
  "删除提示词": "プロンプトを削除",
  "取消": "キャンセル",
  "保存": "保存",
  "完成": "完了",
  "更改后自动保存": "変更は自動保存されます",
  "呼出快捷键": "ショートカット",
  "浮窗大小": "ウィンドウサイズ",
  "小": "小",
  "中": "中",
  "大": "大",
  "外观": "外観",
  "语言": "言語",
  "跟随系统": "システムに従う",
  "浅色": "ライト",
  "深色": "ダーク",
  "登录时启动": "ログイン時に起動",
  "辅助功能权限": "アクセシビリティ",
  "配置文件": "設定ファイル",
  "打开": "開く",
  "已授权 ›": "許可済み ›",
  "去授权 ›": "許可する ›",
  "请在系统设置中批准登录项": "システム設定でログイン項目を許可してください",
  "没有匹配的提示词": "一致するプロンプトがありません",
  "还没有提示词": "プロンプトはまだありません",
  " 条": " 件",
  " 字符": " 文字",
  "已保存": "保存済み",
  "未保存": "未保存",
  "已删除": "削除済み",
  "请输入提示词正文": "本文を入力してください",
  "放弃未保存的修改？": "未保存の変更を破棄しますか？",
  "当前修改尚未保存。": "変更は保存されていません。",
  "放弃修改": "破棄",
  "继续编辑": "編集を続ける",
  "删除这条提示词？": "このプロンプトを削除しますか？",
  "删除后无法恢复。": "この操作は取り消せません。",
  "删除": "削除",
  "按下组合键…": "キーを押してください…",
  "请包含 ⌘ / ⌃ / ⌥": "⌘ / ⌃ / ⌥ を含めてください",
  "提示词": "プロンプト",
  "纯文本": "プレーンテキスト",
  "编辑": "編集",
  "插入": "挿入",
  "返回": "戻る",
  "新建": "新規",
  "新建提示词（⌘N）": "新規プロンプト (⌘N)",
  "编辑提示词（⌘E）": "プロンプトを編集 (⌘E)",
  "设置（⌘,）": "設定 (⌘,)",
  "⌘S 保存": "⌘S 保存",
  "⌃B 返回": "⌃B 戻る",
  "⌘N 新建 · ⌘E 编辑 · ↵ 插入": "⌘N 新規 · ⌘E 編集 · ↵ 挿入"
 },
 "ko": {
  "搜索短语": "문구 검색",
  "搜索提示词": "프롬프트 검색",
  "新建提示词": "새 프롬프트",
  "编辑提示词": "프롬프트 편집",
  "设置": "설정",
  "返回提示词": "목록으로 돌아가기",
  "提示词正文": "프롬프트 내용",
  "输入提示词正文…": "내용 입력…",
  "置顶": "고정",
  "删除提示词": "프롬프트 삭제",
  "取消": "취소",
  "保存": "저장",
  "完成": "완료",
  "更改后自动保存": "변경 사항이 자동 저장됩니다",
  "呼出快捷键": "단축키",
  "浮窗大小": "창 크기",
  "小": "작게",
  "中": "보통",
  "大": "크게",
  "外观": "화면 모드",
  "语言": "언어",
  "跟随系统": "시스템 설정",
  "浅色": "라이트",
  "深色": "다크",
  "登录时启动": "로그인 시 실행",
  "辅助功能权限": "손쉬운 사용 권한",
  "配置文件": "설정 파일",
  "打开": "열기",
  "已授权 ›": "허용됨 ›",
  "去授权 ›": "권한 허용 ›",
  "请在系统设置中批准登录项": "시스템 설정에서 로그인 항목을 허용하세요",
  "没有匹配的提示词": "일치하는 프롬프트가 없습니다",
  "还没有提示词": "아직 프롬프트가 없습니다",
  " 条": "개",
  " 字符": "자",
  "已保存": "저장됨",
  "未保存": "저장 안 됨",
  "已删除": "삭제됨",
  "请输入提示词正文": "내용을 입력하세요",
  "放弃未保存的修改？": "저장하지 않은 변경 사항을 버릴까요?",
  "当前修改尚未保存。": "변경 사항이 저장되지 않았습니다.",
  "放弃修改": "버리기",
  "继续编辑": "계속 편집",
  "删除这条提示词？": "이 프롬프트를 삭제할까요?",
  "删除后无法恢复。": "이 작업은 되돌릴 수 없습니다.",
  "删除": "삭제",
  "按下组合键…": "단축키를 누르세요…",
  "请包含 ⌘ / ⌃ / ⌥": "⌘ / ⌃ / ⌥를 포함하세요",
  "提示词": "프롬프트",
  "纯文本": "일반 텍스트",
  "编辑": "편집",
  "插入": "삽입",
  "返回": "뒤로",
  "新建": "새로 만들기",
  "新建提示词（⌘N）": "새 프롬프트 (⌘N)",
  "编辑提示词（⌘E）": "프롬프트 편집 (⌘E)",
  "设置（⌘,）": "설정 (⌘,)",
  "⌘S 保存": "⌘S 저장",
  "⌃B 返回": "⌃B 뒤로",
  "⌘N 新建 · ⌘E 编辑 · ↵ 插入": "⌘N 새로 만들기 · ⌘E 편집 · ↵ 삽입"
 },
 "fr": {
  "搜索短语": "Rechercher des expressions",
  "搜索提示词": "Rechercher des prompts",
  "新建提示词": "Nouveau prompt",
  "编辑提示词": "Modifier le prompt",
  "设置": "Réglages",
  "返回提示词": "Retour aux prompts",
  "提示词正文": "Texte du prompt",
  "输入提示词正文…": "Saisir le texte…",
  "置顶": "Épingler",
  "删除提示词": "Supprimer le prompt",
  "取消": "Annuler",
  "保存": "Enregistrer",
  "完成": "Terminé",
  "更改后自动保存": "Enregistrement automatique",
  "呼出快捷键": "Raccourci",
  "浮窗大小": "Taille de fenêtre",
  "小": "P",
  "中": "M",
  "大": "G",
  "外观": "Apparence",
  "语言": "Langue",
  "跟随系统": "Système",
  "浅色": "Clair",
  "深色": "Sombre",
  "登录时启动": "Ouvrir à la connexion",
  "辅助功能权限": "Accessibilité",
  "配置文件": "Configuration",
  "打开": "Ouvrir",
  "已授权 ›": "Autorisé ›",
  "去授权 ›": "Autoriser ›",
  "请在系统设置中批准登录项": "Autorisez l’ouverture à la connexion dans les Réglages Système",
  "没有匹配的提示词": "Aucun résultat",
  "还没有提示词": "Aucun prompt",
  " 条": " prompts",
  " 字符": " caractères",
  "已保存": "Enregistré",
  "未保存": "Non enregistré",
  "已删除": "Supprimé",
  "请输入提示词正文": "Saisissez le texte du prompt",
  "放弃未保存的修改？": "Abandonner les modifications ?",
  "当前修改尚未保存。": "Les modifications ne sont pas enregistrées.",
  "放弃修改": "Abandonner",
  "继续编辑": "Continuer à modifier",
  "删除这条提示词？": "Supprimer ce prompt ?",
  "删除后无法恢复。": "Cette action est irréversible.",
  "删除": "Supprimer",
  "按下组合键…": "Appuyez sur les touches…",
  "请包含 ⌘ / ⌃ / ⌥": "Inclure ⌘ / ⌃ / ⌥",
  "提示词": "Prompt",
  "纯文本": "Texte brut",
  "编辑": "Modifier",
  "插入": "Insérer",
  "返回": "Retour",
  "新建": "Nouveau",
  "新建提示词（⌘N）": "Nouveau prompt (⌘N)",
  "编辑提示词（⌘E）": "Modifier le prompt (⌘E)",
  "设置（⌘,）": "Réglages (⌘,)",
  "⌘S 保存": "⌘S Enregistrer",
  "⌃B 返回": "⌃B Retour",
  "⌘N 新建 · ⌘E 编辑 · ↵ 插入": "⌘N Nouveau · ⌘E Modifier · ↵ Insérer"
 },
 "de": {
  "搜索短语": "Phrasen suchen",
  "搜索提示词": "Prompts suchen",
  "新建提示词": "Neuer Prompt",
  "编辑提示词": "Prompt bearbeiten",
  "设置": "Einstellungen",
  "返回提示词": "Zurück zur Liste",
  "提示词正文": "Prompt-Text",
  "输入提示词正文…": "Text eingeben…",
  "置顶": "Anheften",
  "删除提示词": "Prompt löschen",
  "取消": "Abbrechen",
  "保存": "Speichern",
  "完成": "Fertig",
  "更改后自动保存": "Änderungen automatisch gespeichert",
  "呼出快捷键": "Kurzbefehl",
  "浮窗大小": "Fenstergröße",
  "小": "K",
  "中": "M",
  "大": "G",
  "外观": "Darstellung",
  "语言": "Sprache",
  "跟随系统": "System",
  "浅色": "Hell",
  "深色": "Dunkel",
  "登录时启动": "Beim Anmelden starten",
  "辅助功能权限": "Bedienungshilfen",
  "配置文件": "Konfiguration",
  "打开": "Öffnen",
  "已授权 ›": "Erlaubt ›",
  "去授权 ›": "Erlauben ›",
  "请在系统设置中批准登录项": "Anmeldeobjekt in den Systemeinstellungen erlauben",
  "没有匹配的提示词": "Keine passenden Prompts",
  "还没有提示词": "Noch keine Prompts",
  " 条": " Prompts",
  " 字符": " Zeichen",
  "已保存": "Gespeichert",
  "未保存": "Nicht gespeichert",
  "已删除": "Gelöscht",
  "请输入提示词正文": "Bitte Prompt-Text eingeben",
  "放弃未保存的修改？": "Änderungen verwerfen?",
  "当前修改尚未保存。": "Änderungen wurden nicht gespeichert.",
  "放弃修改": "Verwerfen",
  "继续编辑": "Weiter bearbeiten",
  "删除这条提示词？": "Diesen Prompt löschen?",
  "删除后无法恢复。": "Dies kann nicht rückgängig gemacht werden.",
  "删除": "Löschen",
  "按下组合键…": "Tastenkombination drücken…",
  "请包含 ⌘ / ⌃ / ⌥": "⌘ / ⌃ / ⌥ verwenden",
  "提示词": "Prompt",
  "纯文本": "Nur Text",
  "编辑": "Bearbeiten",
  "插入": "Einfügen",
  "返回": "Zurück",
  "新建": "Neu",
  "新建提示词（⌘N）": "Neuer Prompt (⌘N)",
  "编辑提示词（⌘E）": "Prompt bearbeiten (⌘E)",
  "设置（⌘,）": "Einstellungen (⌘,)",
  "⌘S 保存": "⌘S Speichern",
  "⌃B 返回": "⌃B Zurück",
  "⌘N 新建 · ⌘E 编辑 · ↵ 插入": "⌘N Neu · ⌘E Bearbeiten · ↵ Einfügen"
 },
 "es": {
  "搜索短语": "Buscar frases",
  "搜索提示词": "Buscar prompts",
  "新建提示词": "Nuevo prompt",
  "编辑提示词": "Editar prompt",
  "设置": "Ajustes",
  "返回提示词": "Volver a los prompts",
  "提示词正文": "Texto del prompt",
  "输入提示词正文…": "Escribe el texto…",
  "置顶": "Fijar",
  "删除提示词": "Eliminar prompt",
  "取消": "Cancelar",
  "保存": "Guardar",
  "完成": "Listo",
  "更改后自动保存": "Los cambios se guardan automáticamente",
  "呼出快捷键": "Atajo",
  "浮窗大小": "Tamaño de ventana",
  "小": "P",
  "中": "M",
  "大": "G",
  "外观": "Apariencia",
  "语言": "Idioma",
  "跟随系统": "Sistema",
  "浅色": "Claro",
  "深色": "Oscuro",
  "登录时启动": "Abrir al iniciar sesión",
  "辅助功能权限": "Accesibilidad",
  "配置文件": "Configuración",
  "打开": "Abrir",
  "已授权 ›": "Permitido ›",
  "去授权 ›": "Permitir ›",
  "请在系统设置中批准登录项": "Autoriza el inicio de sesión en Ajustes del Sistema",
  "没有匹配的提示词": "No hay coincidencias",
  "还没有提示词": "Aún no hay prompts",
  " 条": " prompts",
  " 字符": " caracteres",
  "已保存": "Guardado",
  "未保存": "Sin guardar",
  "已删除": "Eliminado",
  "请输入提示词正文": "Escribe el texto del prompt",
  "放弃未保存的修改？": "¿Descartar los cambios?",
  "当前修改尚未保存。": "Los cambios no se han guardado.",
  "放弃修改": "Descartar",
  "继续编辑": "Seguir editando",
  "删除这条提示词？": "¿Eliminar este prompt?",
  "删除后无法恢复。": "Esta acción no se puede deshacer.",
  "删除": "Eliminar",
  "按下组合键…": "Pulsa las teclas…",
  "请包含 ⌘ / ⌃ / ⌥": "Incluye ⌘ / ⌃ / ⌥",
  "提示词": "Prompt",
  "纯文本": "Texto sin formato",
  "编辑": "Editar",
  "插入": "Insertar",
  "返回": "Volver",
  "新建": "Nuevo",
  "新建提示词（⌘N）": "Nuevo prompt (⌘N)",
  "编辑提示词（⌘E）": "Editar prompt (⌘E)",
  "设置（⌘,）": "Ajustes (⌘,)",
  "⌘S 保存": "⌘S Guardar",
  "⌃B 返回": "⌃B Volver",
  "⌘N 新建 · ⌘E 编辑 · ↵ 插入": "⌘N Nuevo · ⌘E Editar · ↵ Insertar"
 }
};
function t(text){return interfaceLanguage==='zh-Hans' ? text : (translatedText[interfaceLanguage]?.[text] || englishText[text] || text)}
let staticLabels=[];
function captureStaticLabels(){
 const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);
 while(walker.nextNode()){
  const node=walker.currentNode;
  if(node.parentElement.closest('script,style'))continue;
  const key=node.nodeValue.trim();
  if(englishText[key])staticLabels.push(()=>{node.nodeValue=t(key)});
 }
 document.querySelectorAll('[aria-label],[placeholder],[title]').forEach(el=>{
  for(const attr of ['aria-label','placeholder','title']){
   const key=el.getAttribute(attr);
   if(englishText[key])staticLabels.push(()=>el.setAttribute(attr,t(key)));
  }
 });
}
function localizeStatic(){document.documentElement.lang=interfaceLanguage;staticLabels.forEach(apply=>apply())}
